import {sections, createEntry, createField} from "./snippets"

// ENTRIES
export const biblatexEntrySnippets = [
    // // Recommended Entries
    // createEntry("article", sections.Recommended, "An article in a periodical.", ["author", "title", "journal", "date"]),
    // createEntry("book", sections.Recommended, "A single-volume book.", ["author", "title", "date"]),
    // createEntry("booklet", sections.Recommended, "A book-like work without a formal publisher.", ["author", "title", "date"]),
    // createEntry("collection", sections.Recommended, "A single-volume collection.", ["editor", "title", "date"]),
    // createEntry("dataset", sections.Recommended, "A data set or similar collection of raw data.", ["editor", "title", "date"]),
    // createEntry("manual", sections.Recommended, "Technical or other documentation.", ["author", "title", "date"]),
    // createEntry("online", sections.Recommended, "An online resource.", ["author", "title", "date", "url"]),
    // createEntry("patent", sections.Recommended, "A patent or patent request.", ["author", "title", "number", "date"]),
    // createEntry("periodical", sections.Recommended, "A complete issue of a periodical.", ["editor", "title", "date"]),
    // createEntry("proceedings", sections.Recommended, "A single-volume conference proceedings.", ["title", "date"]),
    // createEntry("reference", sections.Recommended, "A single-volume work of reference.", ["editor", "title", "date"]),
    // createEntry("report", sections.Recommended, "A report of some kind published by an institution.", ["author", "title", "type", "institution", "date"]),
    // createEntry("software", sections.Recommended, "A piece of computer software.", ["author", "title", "date"]),
    // createEntry("thesis", sections.Recommended, "A thesis written for an educational institution.", ["author", "title", "type", "institution", "date"]),
    //
    // // Optional Entries
    // createEntry("artwork", sections.Optional, "A work of the visual arts.", ["author", "title", "date"]),
    // createEntry("audio", sections.Optional, "An audio recording.", ["author", "title", "date"]),
    // createEntry("bookinbook", sections.Optional, "An <@inbook> that was originally published as its own work.", ["author", "title", "booktitle", "date"]),
    // createEntry("commentary", sections.Optional, "A legal or other commentary.", ["author", "title", "date"]),
    // createEntry("image", sections.Optional, "An image or similar media.", ["author", "title", "date"]),
    // createEntry("inbook", sections.Optional, "A part of a book which is its own titled work.", ["author", "title", "booktitle", "date"]),
    // createEntry("incollection", sections.Optional, "A contribution to a collection which is its own titled work.", ["author", "title", "editor", "booktitle", "date"]),
    // createEntry("inproceedings", sections.Optional, "An article in a conference proceedings.", ["author", "title", "booktitle", "date"]),
    // createEntry("inreference", sections.Optional, "An article in a work of reference.", ["editor", "title", "date"]),
    // createEntry("jurisdiction", sections.Optional, "A court decision, recording, or similar.", ["author", "title", "date"]),
    // createEntry("legal", sections.Optional, "A legal document such as a treaty.", ["organization", "title", "date"]),
    // createEntry("legislation", sections.Optional, "A law, bill, proposal, or similar.", ["organization", "title", "date"]),
    // createEntry("letter", sections.Optional, "Personal correspondence.", ["author", "title", "date"]),
    // createEntry("misc", sections.Special, "A fallback for entries which do not fit in other categories.", ["author", "title", "date"]),
    // createEntry("movie", sections.Optional, "A motion picture.", ["publisher", "title", "date"]),
    // createEntry("music", sections.Optional, "A musical recording.", ["publisher", "title", "date"]),
    // createEntry("mvbook", sections.Optional, "A multi-volume book.", ["author", "title", "date"]),
    // createEntry("mvcollection", sections.Optional, "A multi-volume collection.", ["editor", "title", "date"]),
    // createEntry("mvproceedings", sections.Optional, "A multi-volume conference proceedings.", ["title", "date"]),
    // createEntry("mvreference", sections.Optional, "A multi-volume work of reference.", ["editor", "title", "date"]),
    // createEntry("performance", sections.Optional, "A work of the performing arts.", ["organization", "title", "date"]),
    // createEntry("review", sections.Optional, "A review of some other work.", ["author", "title", "journal", "date"]),
    // createEntry("standard", sections.Optional, "A National or Institutional standard issued by a standards body.", ["organization", "title", "date"]),
    // createEntry("suppbook", sections.Optional, "Supplemental material in a book.", ["author", "title", "booktitle", "date"]),
    // createEntry("suppcollection", sections.Optional, "Supplemental material in a collection.", ["editor", "title", "date"]),
    // createEntry("suppperiodical", sections.Optional, "Supplemental material in a periodical.", ["editor", "title", "date"]),
    // createEntry("unpublished", sections.Optional, "A work which has not been formally published.", ["author", "title", "date"]),
    // createEntry("video", sections.Optional, "An audiovisual recording.", ["author", "title", "date"]),
    //
    // // Special Entries
    // createEntry("bibnote", sections.Special, "Used by the `notes2bib` package (and others) to place notes within the bibliography.", ["note"]),
    // createEntry("custom", sections.Special, "Custom types for special bibliography styles.", []),
    // createEntry("set", sections.Special, "An entry set.", ["entryset"]),
    // createEntry("xdata", sections.Special, "Holds data which may be inherited by other entries using the <xdata> field.", []),
    //
    // // Entry Aliases (mostly for backwards compatibility with BibTeX)
    // createEntry("conference", sections.Alias, "An alias for <@inproceedings>.", ["author", "title", "booktitle", "date"]),
    // createEntry("electronic", sections.Alias, "An alias for <@online>.", ["author", "title", "date", "url"]),
    // createEntry("mastersthesis", sections.Alias, "An alias for <@thesis>.", ["author", "title", "institution", "date"]),
    // createEntry("phdthesis", sections.Alias, "An alias for <@thesis>.", ["author", "title", "institution", "date"]),
    // createEntry("techreport", sections.Alias, "An alias for <@report>.", ["author", "title", "institution", "date"]),
    // createEntry("www", sections.Alias, "An alias for <@online>.", ["author", "title", "date", "url"]),
];

// FIELDS
export const biblatexFieldSnippets = [
    // Recommended Fields
    createField("author", sections.Recommended, "The author(s) of <title>."),
    createField("title", sections.Recommended, "The title of the work."),
    createField("publisher", sections.Recommended, "The name(s) of the publisher(s)."),
    createField("date", sections.Recommended, "The publication date."),
    createField("doi", sections.Recommended, "The Digital Object Identifier of the work."),
    createField("url", sections.Recommended, "The url of an online publication."),
    createField("urldate", sections.Recommended, "The access date of the <url>."),

    // Optional Fields
    createField("abstract", sections.Optional, "The abstract of the work being cited."),
    createField("addendum", sections.Optional, "Miscellaneous bibliographic data."),
    createField("afterword", sections.Optional, "The author(s) of an afterword to the work."),
    createField("annotation", sections.Optional, "An annotation for use in annotated bibliographies."),
    createField("annotator", sections.Optional, "The author(s) of annotations within the work."),
    createField("authortype", sections.Optional, "The type of <author>."),
    createField("bookauthor", sections.Optional, "The author(s) of <booktitle>"),
    createField("bookpagination", sections.Optional, "The pagination scheme of the enclosing work."),
    createField("booksubtitle", sections.Optional, "The subtitle related to the <booktitle>."),
    createField("booktitle", sections.Optional, "The title of a work which is part of a larger publication."),
    createField("booktitleaddon", sections.Optional, "An annex to the <booktitle>."),
    createField("chapter", sections.Optional, "A chapter or section or any other unit of a work."),
    createField("commentator", sections.Optional, "The author(s) of a commentary to the work."),
    createField("edition", sections.Optional, "The edition of a printed publication, as an integer."),
    createField("editor", sections.Optional, "The editor(s) of the work."),
    createField("editora", sections.Optional, "The secondary editor(s), performing a different editorial role."),
    createField("editorb", sections.Optional, "More secondary editor(s), performing a different role."),
    createField("editorc", sections.Optional, "More secondary editor(s), performing a different role."),
    createField("editortype", sections.Optional, "The type of editorial role performed by <editor>."),
    createField("editoratype", sections.Optional, "The type of editorial role performed by <editora>."),
    createField("editorbtype", sections.Optional, "The type of editorial role performed by <editorb>."),
    createField("editorctype", sections.Optional, "The type of editorial role performed by <editorc>."),
    createField("eid", sections.Optional, "The Electronic Identifier of a section of a larger work."),
    createField("entrysubtype", sections.Optional, "The subtype of an entry type."),
    createField("eprint", sections.Optional, "The Electronic Identifier of an online publication."),
    createField("eprintclass", sections.Optional, "Additional information related to the <eprinttype>."),
    createField("eprinttype", sections.Optional, "The type of <eprint> identifier."),
    createField("eventdate", sections.Optional, "The date of an event in a <@proceedings> entry."),
    createField("eventtitle", sections.Optional, "The title of an event in a <@proceedings> entry."),
    createField("eventtitleaddon", sections.Optional, "An annex to the <eventtitle>."),
    createField("file", sections.Optional, "A local link to a file containing the work."),
    createField("foreword", sections.Optional, "The author(s) of a foreword to the work."),
    createField("holder", sections.Optional, "The holder(s) of a <@patent>."),
    createField("howpublished", sections.Optional, "A publication notice for unusual publications."),
    createField("indextitle", sections.Optional, "A title to use for indexing instead of the regular <title>."),
    createField("institution", sections.Optional, "The name of a university or some other institution."),
    createField("introduction", sections.Optional, "The author(s) of an introduction to the work."),
    createField("isan", sections.Optional, "The International Standard Audiovisual Number of an audiovisual work."),
    createField("isbn", sections.Optional, "The International Standard Book Number of a book."),
    createField("ismn", sections.Optional, "The International Standard Music Number of a piece of printed music."),
    createField("isrn", sections.Optional, "The International Standard Technical Report Number of a technical report."),
    createField("issn", sections.Optional, "The International Standard Serial Number of a periodical."),
    createField("issue", sections.Optional, "The issue of a journal or other periodical."),
    createField("issuesubtitle", sections.Optional, "The subtitle of a specific issue of a periodical."),
    createField("issuetitle", sections.Optional, "The title of a specific issue of a periodical."),
    createField("issuetitleaddon", sections.Optional, "An annex to the <issuetitle>."),
    createField("iswc", sections.Optional, "The International Standard Work Code of a musical work."),
    createField("journalsubtitle", sections.Optional, "The subtitle of a periodical."),
    createField("journaltitle", sections.Optional, "The title of a periodical."),
    createField("journaltitleaddon", sections.Optional, "An annex to the <journaltitle>."),
    createField("label", sections.Optional, "A fallback for the auto-generated label."),
    createField("language", sections.Optional, "The language(s) of the work."),
    createField("library", sections.Optional, "The library name and/or call number."),
    createField("location", sections.Optional, "The place(s) of publication."),
    createField("mainsubtitle", sections.Optional, "The subtitle related to the <maintitle>."),
    createField("maintitle", sections.Optional, "The main title of a multi-volume publication."),
    createField("maintitleaddon", sections.Optional, "An annex to the <maintitle>."),
    createField("nameaddon", sections.Optional, "An addon to be printed after the author name."),
    createField("note", sections.Optional, "Miscellaenous bibliographic data which does not fit into any other field."),
    createField("number", sections.Optional, "The number or volume number of a periodical or other work in a series."),
    createField("organization", sections.Optional, "The organization(s) that published or sponsored a work."),
    createField("origdate", sections.Optional, "The publication date of the original edition of a work."),
    createField("origlanguage", sections.Optional, "The language(s) of the original edition of a work."),
    createField("origlocation", sections.Optional, "The place(s) of publication of the original edition of a work."),
    createField("origpublisher", sections.Optional, "The publisher of the original edition of a work."),
    createField("origtitle", sections.Optional, "The title of the original edition of a work."),
    createField("pages", sections.Optional, "One or more page numbers or page ranges."),
    createField("pagetotal", sections.Optional, "The total number of pages of the work."),
    createField("pagination", sections.Optional, "The pagination of the work."),
    createField("part", sections.Optional, "The number of a partial volume."),
    createField("pubstate", sections.Optional, "The publication state of the work."),
    createField("reprinttitle", sections.Optional, "The title of a reprint of the work."),
    createField("series", sections.Optional, "The name of a publication series or the number of a periodical series."),
    createField("shortauthor", sections.Optional, "The author(s) of the work, given in an abbreviated form."),
    createField("shorteditor", sections.Optional, "The editor(s) of the work, given in an abbreviated form."),
    createField("shorthand", sections.Optional, "An override for the auto-generated label."),
    createField("shorthandintro", sections.Optional, "An override for the standard introduction for shorthand citations."),
    createField("shortjournal", sections.Optional, "A short version or acronym of the <journal title>."),
    createField("shortseries", sections.Optional, "A short version or acronym of the <series>."),
    createField("shorttitle", sections.Optional, "A short version or acronym of the <title>."),
    createField("subtitle", sections.Optional, "The subtitle of the work."),
    createField("titleaddon", sections.Optional, "An annex to the <title>."),
    createField("translator", sections.Optional, "The translator(s) of the work."),
    createField("type", sections.Optional, "The type of a work."),
    createField("venue", sections.Optional, "The location of an event in a <@proceedings> entry."),
    createField("version", sections.Optional, "The revision number of a work."),
    createField("volume", sections.Optional, "The volume number of a series or periodical, as an integer."),
    createField("volumes", sections.Optional, "The total number of volumes of a series, as an integer."),
    // WARN: opinion: exclude `month` and `year` fields as the user gets significantly more functionality from the `date` field
    // createField("month", sections.Optional, "The month of publication."),
    // createField("year", sections.Optional, "The year of publication."),

    // Special Fields
    createField("crossref", sections.Special, "An entry key for the cross-referencing feature."),
    createField("entryset", sections.Special, "A set of entry keys."),
    createField("gender", sections.Special, "The gender of the author(s) or editor(s)."),
    createField("langid", sections.Special, "The language id of the entry."),
    createField("langidopts", sections.Special, "Specific language options for the entry."),
    createField("ids", sections.Special, "Aliases for the main citation key."),
    createField("indexsorttitle", sections.Special, "The title used when sorting the index."),
    createField("keywords", sections.Special, "A separated list of keywords."),
    createField("options", sections.Special, "A separated list of entry options."),
    createField("presort", sections.Special, "Used to modify the sorting order of the bibliography. (Takes precedence over sortkey.)"),
    createField("related", sections.Special, "Citation keys of other related entries."),
    createField("relatedoptions", sections.Special, "Per-type options to set for a related entry."),
    createField("relatedtype", sections.Special, "The type of relationship for entry in <related>."),
    createField("relatedstring", sections.Special, "An override for the bibliography string from <relatedtype>."),
    createField("sortkey", sections.Special, "Used to modify the sorting order of the bibliography."),
    createField("sortname", sections.Special, "A name used to modify the sorting order of the bibliography."),
    createField("sortshorthand", sections.Special, "Used to modify the sorting order of the list of shorthands."),
    createField("sorttitle", sections.Special, "A title used to modify the sorting order of the bibliography."),
    createField("xdata", sections.Special, "Inherits data from one or more specified entry keys."),
    createField("xref", sections.Special, "Cross-references from one or more specified entry keys."),
    // WARN: opinion: exclude `sortyear` field for the same reason as the `month` and `year` exclusions
    // createField("sortyear", sections.Special, "A year used to modify the sorting order of the bibliography."),
    // WARN: `execute` allows arbitrary LaTeX code execution when building file, don't necessarily want users having access to this
    // createField("execute", sections.Special, "Arbitrary LaTeX code to be executed."),

    // Field Aliases (mostly for backwards compatibility with BibTeX)
    createField("address", sections.Alias, "An alias for <location>."),
    createField("annote", sections.Alias, "An alias for <annotation>."),
    createField("archiveprefix", sections.Alias, "An alias for <eprinttype>."),
    createField("journal", sections.Alias, "An alias for <journaltitle>."),
    createField("key", sections.Alias, "An alias for <sortkey>."),
    createField("pdf", sections.Alias, "An alias for <file>."),
    createField("primaryclass", sections.Alias, "An alias for <eprintclass>."),
    createField("school", sections.Alias, "An alias for <institution>.")
];

/// A complete ([opinionated](https://www.citedrive.com/en/blog/codemirror-bibtex-plugin)) collection of BibLaTeX autocomplete [snippets](#autocomplete.snippet).
export const biblatexSnippets = biblatexEntrySnippets.concat(biblatexFieldSnippets);
