import {createEntry, createField} from "./snippets"

// ENTRIES
export const biblatexEntrySnippets = [
    // Standard Entries
    createEntry("article", "An article in a periodical.", ["author", "title", "journal", "date"]),
    createEntry("book", "A single-volume book.", ["author", "title", "date"]),
    createEntry("mvbook", "A multi-volume book.", ["author", "title", "date"]),
    createEntry("inbook", "A part of a book which is its own titled work.", ["author", "title", "booktitle", "date"]),
    createEntry("bookinbook", "An <@inbook> that was originally published as its own work.", ["author", "title", "booktitle", "date"]),
    createEntry("suppbook", "Supplemental material in a book.", ["author", "title", "booktitle", "date"]),
    createEntry("booklet", "A book-like work without a formal publisher.", ["author", "title", "date"]),
    createEntry("collection", "A single-volume collection.", ["editor", "title", "date"]),
    createEntry("mvcollection", "A multi-volume collection.", ["editor", "title", "date"]),
    createEntry("incollection", "A contribution to a collection which is its own titled work.", ["author", "title", "editor", "booktitle", "date"]),
    createEntry("suppcollection", "Supplemental material in a collection.", ["editor", "title", "date"]),
    createEntry("dataset", "A data set or similar collection of raw data.", ["editor", "title", "date"]),
    createEntry("manual", "Technical or other documentation.", ["author", "title", "date"]),
    createEntry("misc", "A fallback for entries which do not fit in other categories.", ["author", "title", "date"]),
    createEntry("online", "An online resource.", ["author", "title", "date", "url"]),
    createEntry("patent", "A patent or patent request.", ["author", "title", "number", "date"]),
    createEntry("periodical", "A complete issue of a periodical.", ["editor", "title", "date"]),
    createEntry("suppperiodical", "Supplemental material in a periodical.", ["editor", "title", "date"]),
    createEntry("proceedings", "A single-volume conference proceedings.", ["title", "date"]),
    createEntry("mvproceedings", "A multi-volume conference proceedings.", ["title", "date"]),
    createEntry("inproceedings", "An article in a conference proceedings.", ["author", "title", "booktitle", "date"]),
    createEntry("reference", "A single-volume work of reference.", ["editor", "title", "date"]),
    createEntry("mvreference", "A multi-volume work of reference.", ["editor", "title", "date"]),
    createEntry("inreference", "An article in a work of reference.", ["editor", "title", "date"]),
    createEntry("report", "A report of some kind published by an institution.", ["author", "title", "type", "institution", "date"]),
    createEntry("set", "An entry set.", ["entryset"]),
    createEntry("software", "A piece of computer software.", ["author", "title", "date"]),
    createEntry("thesis", "A thesis written for an educational institution.", ["author", "title", "type", "institution", "date"]),
    createEntry("unpublished", "A work which has not been formally published.", ["author", "title", "date"]),

    // Special Entries
    createEntry("artwork", "A work of the visual arts.", ["author", "title", "date"]),
    createEntry("audio", "An audio recording.", ["author", "title", "date"]),
    createEntry("commentary", "A legal or other commentary.", ["author", "title", "date"]),
    createEntry("image", "An image or similar media.", ["author", "title", "date"]),
    createEntry("jurisdiction", "A court decision, recording, or similar.", ["author", "title", "date"]),
    createEntry("legal", "A legal document such as a treaty.", ["organization", "title", "date"]),
    createEntry("legislation", "A law, bill, proposal, or similar.", ["organization", "title", "date"]),
    createEntry("letter", "Personal correspondence.", ["author", "title", "date"]),
    createEntry("movie", "A motion picture.", ["publisher", "title", "date"]),
    createEntry("music", "A musical recording.", ["publisher", "title", "date"]),
    createEntry("performance", "A work of the performing arts.", ["organization", "title", "date"]),
    createEntry("review", "A review of some other work.", ["author", "title", "journal", "date"]),
    createEntry("standard", "A National or Institutional standard issued by a standards body.", ["organization", "title", "date"]),
    createEntry("video", "An audiovisual recording.", ["author", "title", "date"]),

    // Entry Aliases (mostly for backwards compatibility with BibTeX)
    createEntry("conference", "An alias for <@inproceedings>.", ["author", "title", "booktitle", "date"]),
    createEntry("electronic", "An alias for <@online>.", ["author", "title", "date", "url"]),
    createEntry("mastersthesis", "An alias for <@thesis>.", ["author", "title", "institution", "date"]),
    createEntry("phdthesis", "An alias for <@thesis>.", ["author", "title", "institution", "date"]),
    createEntry("techreport", "An alias for <@report>.", ["author", "title", "institution", "date"]),
    createEntry("www", "An alias for <@online>.", ["author", "title", "date", "url"]),
];

// FIELDS
export const biblatexFieldSnippets = [
    // Standard Fields
    createField("abstract", "The abstract of the work being cited."),
    createField("addendum", "Miscellaneous bibliographic data."),
    createField("afterword", "The author(s) of an afterword to the work."),
    createField("annotation", "An annotation for use in annotated bibliographies."),
    createField("annotator", "The author(s) of annotations within the work."),
    createField("author", "The author(s) of <title>."),
    createField("authortype", "The type of <author>."),
    createField("bookauthor", "The author(s) of <booktitle>"),
    createField("bookpagination", "The pagination scheme of the enclosing work."),
    createField("booksubtitle", "The subtitle related to the <booktitle>."),
    createField("booktitle", "The title of a work which is part of a larger publication."),
    createField("booktitleaddon", "An annex to the <booktitle>."),
    createField("chapter", "A chapter or section or any other unit of a work."),
    createField("commentator", "The author(s) of a commentary to the work."),
    createField("date", "The publication date."),
    createField("doi", "The Digital Object Identifier of the work."),
    createField("edition", "The edition of a printed publication, as an integer."),
    createField("editor", "The editor(s) of the work."),
    createField("editora", "The secondary editor(s), performing a different editorial role."),
    createField("editorb", "More secondary editor(s), performing a different role."),
    createField("editorc", "More secondary editor(s), performing a different role."),
    createField("editortype", "The type of editorial role performed by <editor>."),
    createField("editoratype", "The type of editorial role performed by <editora>."),
    createField("editorbtype", "The type of editorial role performed by <editorb>."),
    createField("editorctype", "The type of editorial role performed by <editorc>."),
    createField("eid", "The Electronic Identifier of a section of a larger work."),
    createField("entrysubtype", "The subtype of an entry type."),
    createField("eprint", "The Electronic Identifier of an online publication."),
    createField("eprintclass", "Additional information related to the <eprinttype>."),
    createField("eprinttype", "The type of <eprint> identifier."),
    createField("eventdate", "The date of an event in a <@proceedings> entry."),
    createField("eventtitle", "The title of an event in a <@proceedings> entry."),
    createField("eventtitleaddon", "An annex to the <eventtitle>."),
    createField("file", "A local link to a file containing the work."),
    createField("foreword", "The author(s) of a foreword to the work."),
    createField("holder", "The holder(s) of a <@patent>."),
    createField("howpublished", "A publication notice for unusual publications."),
    createField("indextitle", "A title to use for indexing instead of the regular <title>."),
    createField("institution", "The name of a university or some other institution."),
    createField("introduction", "The author(s) of an introduction to the work."),
    createField("isan", "The International Standard Audiovisual Number of an audiovisual work."),
    createField("isbn", "The International Standard Book Number of a book."),
    createField("ismn", "The International Standard Music Number of a piece of printed music."),
    createField("isrn", "The International Standard Technical Report Number of a technical report."),
    createField("issn", "The International Standard Serial Number of a periodical."),
    createField("issue", "The issue of a journal or other periodical."),
    createField("issuesubtitle", "The subtitle of a specific issue of a periodical."),
    createField("issuetitle", "The title of a specific issue of a periodical."),
    createField("issuetitleaddon", "An annex to the <issuetitle>."),
    createField("iswc", "The International Standard Work Code of a musical work."),
    createField("journalsubtitle", "The subtitle of a periodical."),
    createField("journaltitle", "The title of a periodical."),
    createField("journaltitleaddon", "An annex to the <journaltitle>."),
    createField("label", "A fallback for the auto-generated label."),
    createField("language", "The language(s) of the work."),
    createField("library", "The library name and/or call number."),
    createField("location", "The place(s) of publication."),
    createField("mainsubtitle", "The subtitle related to the <maintitle>."),
    createField("maintitle", "The main title of a multi-volume publication."),
    createField("maintitleaddon", "An annex to the <maintitle>."),
    createField("nameaddon", "An addon to be printed after the author name."),
    createField("note", "Miscellaenous bibliographic data which does not fit into any other field."),
    createField("number", "The number or volume number of a periodical or other work in a series."),
    createField("organization", "The organization(s) that published or sponsored a work."),
    createField("origdate", "The publication date of the original edition of a work."),
    createField("origlanguage", "The language(s) of the original edition of a work."),
    createField("origlocation", "The place(s) of publication of the original edition of a work."),
    createField("origpublisher", "The publisher of the original edition of a work."),
    createField("origtitle", "The title of the original edition of a work."),
    createField("pages", "One or more page numbers or page ranges."),
    createField("pagetotal", "The total number of pages of the work."),
    createField("pagination", "The pagination of the work."),
    createField("part", "The number of a partial volume."),
    createField("publisher", "The name(s) of the publisher(s)."),
    createField("pubstate", "The publication state of the work."),
    createField("reprinttitle", "The title of a reprint of the work."),
    createField("series", "The name of a publication series or the number of a periodical series."),
    createField("shortauthor", "The author(s) of the work, given in an abbreviated form."),
    createField("shorteditor", "The editor(s) of the work, given in an abbreviated form."),
    createField("shorthand", "An override for the auto-generated label."),
    createField("shorthandintro", "An override for the standard introduction for shorthand citations."),
    createField("shortjournal", "A short version or acronym of the <journal title>."),
    createField("shortseries", "A short version or acronym of the <series>."),
    createField("shorttitle", "A short version or acronym of the <title>."),
    createField("subtitle", "The subtitle of the work."),
    createField("title", "The title of the work."),
    createField("titleaddon", "An annex to the <title>."),
    createField("translator", "The translator(s) of the work."),
    createField("type", "The type of a work."),
    createField("url", "The url of an online publication."),
    createField("urldate", "The access date of the <url>."),
    createField("venue", "The location of an event in a <@proceedings> entry."),
    createField("version", "The revision number of a work."),
    createField("volume", "The volume number of a series or periodical, as an integer."),
    createField("volumes", "The total number of volumes of a series, as an integer."),
    // WARN: opinion: exclude `month` and `year` from BibLaTeX as the user gets significantly more functionality from the `date` field
    // createField("month", "The month of publication."),
    // createField("year", "The year of publication."),

    // Special Fields
    createField("crossref", "An entry key for the cross-referencing feature."),
    createField("entryset", "A set of entry keys."),
    createField("gender", "The gender of the author(s) or editor(s)."),
    createField("langid", "The language id of the entry."),
    createField("langidopts", "Specific language options for the entry."),
    createField("ids", "Aliases for the main citation key."),
    createField("indexsorttitle", "The title used when sorting the index."),
    createField("keywords", "A separated list of keywords."),
    createField("options", "A separated list of entry options."),
    createField("presort", "Used to modify the sorting order of the bibliography. (Takes precedence over sortkey.)"),
    createField("related", "Citation keys of other related entries."),
    createField("relatedoptions", "Per-type options to set for a related entry."),
    createField("relatedtype", "The type of relationship for entry in <related>."),
    createField("relatedstring", "An override for the bibliography string from <relatedtype>."),
    createField("sortkey", "Used to modify the sorting order of the bibliography."),
    createField("sortname", "A name used to modify the sorting order of the bibliography."),
    createField("sortshorthand", "Used to modify the sorting order of the list of shorthands."),
    createField("sorttitle", "A title used to modify the sorting order of the bibliography."),
    // createField("sortyear", "A year used to modify the sorting order of the bibliography."),
    createField("xdata", "Inherits data from one or more specified entry keys."),
    createField("xref", "Cross-references from one or more specified entry keys."),
    // WARN: `execute` allows arbitrary LaTeX code execution when building file, don't necessarily want users having access to this
    // createField("execute", "Arbitrary LaTeX code to be executed."),

    // Field Aliases (mostly for backwards compatibility with BibTeX)
    createField("address", "An alias for <location>."),
    createField("annote", "An alias for <annotation>."),
    createField("archiveprefix", "An alias for <eprinttype>."),
    createField("journal", "An alias for <journaltitle>."),
    createField("key", "An alias for <sortkey>."),
    createField("pdf", "An alias for <file>."),
    createField("primaryclass", "An alias for <eprintclass>."),
    createField("school", "An alias for <institution>.")
];

/// BibLaTeX autocomplete [snippets](#autocomplete.snippet)
export const biblatexSnippets = biblatexEntrySnippets.concat(biblatexFieldSnippets);
